### PR TITLE
Fix: Unhandled Rejection (error): Not a valid Mint

### PR DESCRIPTION
**Pull request by intelliot**
https://issueexplorer.com/issue/solana-labs/dapp-scaffold/23

### CODE REVIEW

**Comment by Barrendero** [comment]
Just get into src>context>accounts.tsx

rewrite the line 155 with this line

let account; try { account = deserialize(new PublicKey(address), obj); } catch(e) { console.error(e); }

**Comment by vsinha** [comment]
fixes #23

**Comment by barlas** [comment]
yup, I confirmed that fixed the issue in my local

**Comment by barlas** [comment]
this doesn't fix the issue, just gets rid of the error screen.
```
index.js:1 Error: Not a valid Mint
    at deserializeMint (accounts.tsx:615)
    at MintParser (accounts.tsx:48)
    at Object.add (accounts.tsx:157)
    at connection.tsx:119
    at Array.forEach (<anonymous>)
    at connection.tsx:113
```

**Comment by JoshuaFlood** [comment]
This solution is not correct.

The problem is that this error, if it *were* thrown, is not handled.

The error is thrown by `deserializeMint`. This function is only called in one place, at line 48.

A proper solution, as the error message suggests, is to handle the potential error when `deserializeMint` is called.

Therefore, the entire contents of the `MintParser` function, which is where `deserializeMint` is called, should be wrapped inside a `try {} catch {}` statement, like this:

export const MintParser = (pubKey: PublicKey, info: AccountInfo<Buffer>) => {
  try {
    const buffer = Buffer.from(info.data);
    const data = deserializeMint(buffer);

    const details = {
      pubkey: pubKey,
      account: {
        ...info,
      },
      info: data,
    } as ParsedAccountBase;
  
    return details;
  } catch(error) {
    console.error(error);
  }
};

I have submitted a PR here: https://github.com/solana-labs/dapp-scaffold/pull/103

**Pull request closed without merging**
