### PR TITLE
Airdrop Button Spinner

### PR DESCRIPTION
**Pull request by 32jvilla**
Show a spinning loader icon in the UI while the airdrop button awaits a response

https://user-images.githubusercontent.com/61704946/162640950-af192274-7391-4a7e-acce-115b96ce6ad1.mov

Issue #150

Notes
1. I'm unable to generalize this into an intermediary and reusable <ActionButton/> component, because publicKey / useWallet() doesn't seem to work in callback functions

### CODE REVIEW

**Comment by DonnySolana** [comment]
will review and get back with you. thank you for the submission and thought on this!

**Comment by haodev007** [comment]
> Show a spinning loader icon in the UI while the airdrop button awaits a response
> 
>  Demo.mov 
> Issue #150
> 
> Notes
> 
> 1. I'm unable to generalize this into an intermediary and reusable  component, because publicKey / useWallet() doesn't seem to work in callback functions

I think so. We will need loading animation on the button and disable the button while airdropping.
So we can prevent multi request error by not double clicking the airdrop button.
image

**Review by Mohsen-Phoenix — CHANGES_REQUESTED** [review]
F6uEur16fvVHcCXCqwSVAwNk3oVwrKSFvTqScNRrrrR7

**Comment by haodev007** [comment]
Ohh, I think I have to fetch and merge from origin repo. thanks for your hard working!

**Review by haodev007 — CHANGES_REQUESTED** [review]
Awesome!
We should be able to merge it.
It would be great if we have loading spinner.

**Review by DonnySolana — COMMENTED** [review]
where possible the yarn file should not be changing unless necessary for compatibility reasons.  please make sure your yarn updates do not include new changes unless required and mentioned in the update.   otherwise the update is looking good.  thanks!

**Comment by DonnySolana** [comment]
please get latest and re-request if desired to merge into latest wallet updates

**Pull request closed without merging**
